// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CoreHeader {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub version: f32,
    #[prost(string, tag = "3")]
    pub program: ::prost::alloc::string::String,
}
