// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateObjectPerm {
    #[prost(string, tag = "1")]
    pub object: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub owner: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub desc: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub group_read: bool,
    #[prost(bool, tag = "5")]
    pub group_write: bool,
    #[prost(string, repeated, tag = "6")]
    pub groups: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DropObjectPerm {
    #[prost(oneof = "drop_object_perm::Body", tags = "1, 2, 3")]
    pub body: ::core::option::Option<drop_object_perm::Body>,
}
/// Nested message and enum types in `DropObjectPerm`.
pub mod drop_object_perm {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(string, tag = "1")]
        Object(::prost::alloc::string::String),
        #[prost(string, tag = "2")]
        Owner(::prost::alloc::string::String),
        #[prost(string, tag = "3")]
        Groups(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SelectObjectPerm {
    #[prost(string, tag = "1")]
    pub object: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub groups: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DbConnRequestPerm {
    #[prost(oneof = "db_conn_request_perm::Body", tags = "1, 2, 3")]
    pub body: ::core::option::Option<db_conn_request_perm::Body>,
}
/// Nested message and enum types in `DbConnRequestPerm`.
pub mod db_conn_request_perm {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "1")]
        Create(super::CreateObjectPerm),
        #[prost(message, tag = "2")]
        Drop(super::DropObjectPerm),
        #[prost(message, tag = "3")]
        Select(super::SelectObjectPerm),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SelectObjectPermResponse {
    #[prost(string, tag = "1")]
    pub object: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub groups: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub group_read: bool,
    #[prost(bool, tag = "4")]
    pub group_write: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectObjectPermResponses {
    #[prost(message, repeated, tag = "1")]
    pub res: ::prost::alloc::vec::Vec<SelectObjectPermResponse>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbConnResponsePerm {
    #[prost(oneof = "db_conn_response_perm::Body", tags = "1, 2")]
    pub body: ::core::option::Option<db_conn_response_perm::Body>,
}
/// Nested message and enum types in `DbConnResponsePerm`.
pub mod db_conn_response_perm {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(string, tag = "1")]
        Dummy(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        Select(super::SelectObjectPermResponses),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbConnResponse {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<super::core::CoreHeader>,
    #[prost(oneof = "db_conn_response::Body", tags = "2")]
    pub body: ::core::option::Option<db_conn_response::Body>,
}
/// Nested message and enum types in `DbConnResponse`.
pub mod db_conn_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "2")]
        Perm(super::DbConnResponsePerm),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DbConnRequest {
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<super::core::CoreHeader>,
    #[prost(oneof = "db_conn_request::Body", tags = "2")]
    pub body: ::core::option::Option<db_conn_request::Body>,
}
/// Nested message and enum types in `DbConnRequest`.
pub mod db_conn_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "2")]
        Perm(super::DbConnRequestPerm),
    }
}
