syntax = "proto3";

import "core/header.proto";

package dbconn;

message CreateObjectPerm {
  string object = 1;
  string owner  = 2;
  string desc   = 3;

  bool   group_read = 4;
  bool   group_write = 5;

  repeated string groups = 6;
}

message DropObjectPerm {
  oneof body {
    string object = 1;
    string owner  = 2;
    string groups = 3;
  }
}

message SelectObjectPerm {
  string object = 1;
  string groups = 2;
}

message DbConnRequestPerm {
  oneof body {
    CreateObjectPerm create = 1;
    DropObjectPerm drop = 2;
    SelectObjectPerm select = 3;
  }
}

message SelectObjectPermResponse {
  string object = 1;
  string groups = 2;
  bool  group_read = 3;
  bool  group_write = 4;
}

message SelectObjectPermResponses {
  repeated SelectObjectPermResponse res = 1;
}

message DbConnResponsePerm {
  oneof body {
    string dummy = 1;
    SelectObjectPermResponses select= 2;
  }
}